[profile.default]
src = "contracts"
out = ".foundry/artifacts"
libs = [".foundry/lib"]
cache_path = ".foundry/cache"

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = ".foundry/artifacts" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
